---
title: "Stat3616 FP"
author: "Eun Chong Chu"
date: "12/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#library 


```

## Exploring Cancer Dataset

```{r}
#Reading cancer.csv

cancer <- read.csv("cancer_data.csv", header = TRUE)
attach(cancer)
library(ggplot2)
colnames(cancer)
```

#Counting dataset by counting cancer_id per diagnosis type
```{r}
fit <- lm(cancer$id~cancer$diagnosis)
summary(fit)
ggplot(as.data.frame(cancer),aes(factor(diagnosis))) + geom_bar()
```
#Below is the exploration of dataset variables one by one
```{r}
radius_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=radius_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(radius_mean)
#ggplot(as.data.frame(cancer), aes(x=factor(diagnosis), y=area_mean, shape=area_worst, color=area_se)) + geom_point()
fit_radius <- lm(cancer$id ~ cancer$diagnosis + cancer$radius_mean)
summary(fit_radius)
plot(fit_radius)
```

```{r}
texture_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=texture_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(texture_mean)
fit_texture <- lm(cancer$id ~ cancer$diagnosis + cancer$texture_mean)
summary(fit_texture)
plot(fit_texture)
```

```{r}
perimeter_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=perimeter_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(perimeter_mean)
fit_perimeter <- lm(cancer$id ~ cancer$diagnosis + cancer$perimeter_mean)
summary(fit_perimeter)
plot(fit_perimeter)
```

```{r}
area_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=area_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(area_mean)
fit_area <- lm(cancer$id ~ cancer$diagnosis + cancer$area_mean)
summary(fit_area)
plot(fit_area)
```

```{r}
smoothness_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=smoothness_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(smoothness_mean)
fit_smoothness <- lm(cancer$id ~ cancer$diagnosis + cancer$smoothness_mean)
summary(fit_smoothness)
plot(fit_smoothness)
```


```{r}
compactness_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=compactness_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(compactness_mean)
fit_compactness <- lm(cancer$id ~ cancer$diagnosis + cancer$compactness_mean)
summary(fit_compactness)
plot(fit_compactness)
```


```{r}
concavity_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=concavity_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(concavity_mean)
fit_concavity <- lm(cancer$id ~ cancer$diagnosis + cancer$concavity_mean)
summary(fit_concavity)
plot(fit_concavity)
```

```{r}
concave.points_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=concave.points_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(concave.points_mean)
fit_concave.points <- lm(cancer$id ~ cancer$diagnosis + cancer$concave.points_mean)
summary(fit_concave.points)
plot(fit_concave.points)
```

```{r}
symmetry_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=symmetry_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(symmetry_mean)
fit_symmetry <- lm(cancer$id ~ cancer$diagnosis + cancer$symmetry_mean)
summary(fit_symmetry)
plot(fit_symmetry)
```


```{r}
fractal_dimension_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=fractal_dimension_mean)) + geom_boxplot() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(fractal_dimension_mean)
fit_fractal <- lm(cancer$id ~ cancer$diagnosis + cancer$fractal_dimension_mean)
summary(fit_fractal)
plot(fit_fractal)
```





```{r}
fractal_dimension_mean <- ggplot(as.data.frame(cancer),aes(x=factor(diagnosis),y=fractal_dimension_mean)) + geom_point() + geom_smooth(method="lm",se=TRUE, fullrange=FALSE, level=0.95)
plot(fractal_dimension_mean)
fit_fractal <- lm(cancer$id ~ cancer$diagnosis + cancer$fractal_dimension_mean)
summary(fit_fractal)
plot(fit_fractal)
```


######## Wendy ########## 
# correlation

```{r}
mydata<-cancer[, c(3,4,5,6,7,8,9,10,11,12)]
head(mydata)
res<-cor(mydata)
round(res,2)

#heatmap
col<- colorRampPalette(c("blue", "white", "red"))(20)
heatmap(x = res, col = col, symm = TRUE)

#Create the correlation heatmap with ggplot2
#install.packages("reshape2")
library(reshape2)
melted_res<-melt(res)
head(melted_res)
ggplot(data = melted_res, aes(x=Var1, y=Var2, fill=value)) + geom_tile()
get_upper_tri <- function(res){
  res[lower.tri(res)]<- NA
  return(res)}
upper_tri <- get_upper_tri(res)
upper_tri
library(reshape2)
melted_res <- melt(upper_tri, na.rm = TRUE)
# Heatmap
library(ggplot2)
ggplot(data = melted_res, aes(Var2, Var1, fill = value))+ 
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name="Pearson\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 12, hjust = 1))+
  coord_fixed()

melted_res + 
  geom_text(aes(Var2, Var1, label = value), color = "black", size = 4) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.ticks = element_blank(),
    legend.justification = c(1, 0),
    legend.position = c(0.6, 0.7),
    legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
  title.position = "top", title.hjust = 0.5))


#scatter plots
install.packages("PerformanceAnalytics")
library("PerformanceAnalytics")
chart.Correlation(my_data, histogram=TRUE, pch=19)
```




```{r}

mydata<-cancer[, c(3,4,5,6,7,8,9,10,11,12)]
head(mydata)
res<-cor(mydata)
round(res,2)
```

```{r}
library("remotes")
install_github("vqv/ggbiplot")


```

```{r}


library("ggbiplot")


```


```{r}


cancer <- read.csv("C:/Users/lg/Documents/GitHub/stat3612_mbti/cancer_data.csv", header = TRUE)
mydata<-cancer[, c(3,4,5,6,7,8,9,10,11,12)]
cancer.pca<-prcomp(mydata,scale = TRUE)

cancer.pca 
library("ggbiplot")
ggbiplot(cancer.pca) 


```  




```{r}
library(ggplot2)
library(stringr)

url <- "http://s3.amazonaws.com/assets.datacamp.com/production/course_1903/datasets/WisconsinCancer.csv"
# Download the data: wisc.df
wisc.df <- read.csv(url)
str(wisc.df)
# Convert the features of the data: wisc.data
wisc.data <- as.matrix(wisc.df[, 3:32])
str(wisc.data) 
row.names(wisc.data) <- wisc.df$id
head(wisc.data)
diagnosis = as.numeric(wisc.df$diagnosis == "M")
colnames(wisc.data)


## Performing PCA
# Check column means and standard deviations
round(colMeans(wisc.data), 2)
round(apply(wisc.data, 2, sd), 2)
# Execute PCA, scaling if appropriate: wisc.pr
wisc.pr <- prcomp(wisc.data, scale = T, center = T)

# Look at summary of results
summary(wisc.pr) 

#install.packages("remotes")
#remotes::install_github("ssinari/smisc")
## Interpreting PCA results
# Create a biplot of wisc.pr
biplot(wisc.pr)

# Scatter plot observations by components 1 and 2
plot(wisc.pr$x[, c(1, 2)], col = (diagnosis + 1), xlab = "PC1", ylab = "PC2")

# Repeat for components 1 and 3
plot(wisc.pr$x[, c(1, 3)], col = (diagnosis + 1), xlab = "PC1", ylab = "PC3") 


```




```{r}
# We can see from the charts that pc1 and pc2 overlap less than pc1 and pc3.
# This is expected as pc1 and pc2 are meant to be orthogonal and explain different variance

## Variance explained
# Set up 1 x 2 plotting grid
par(mfrow = c(1, 2))

# Calculate variability of each component
pr.var <- wisc.pr$sdev^2

# Variance explained by each principal component: pve
pve <- pr.var / sum(pr.var)

# Plot variance explained for each principal component
plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "b")

# Plot cumulative proportion of variance explained
plot(cumsum(pve), xlab = "Principal Component", 
     ylab = "Cumulative Proportion of Variance Explained", 
     ylim = c(0, 1), type = "b")

``` 



```{r}

## What is the minimum number of principal components required to explain 80% of the variance of the data?
## 5

wisc.pr$rotation[1:10,1:2]
data.scaled <- scale(wisc.data) 


# Calculate the (Euclidean) distances: data.dist
data.dist <- dist(data.scaled)
# Create a hierarchical clustering model: wisc.hclust
wisc.hclust <- hclust(data.dist, method = "complete")
# Results of hierarchical clustering
# cutting the height at 20 will give 4 clusters
plot(wisc.hclust)

## Selecting number of clusters
# Cut tree so that it has 4 clusters: wisc.hclust.clusters
wisc.hclust.clusters <- cutree(wisc.hclust, k = 4)

# Compare cluster membership to actual diagnoses
table(wisc.hclust.clusters, diagnosis)

# count out of place observations based on cluster 
# basically just summing the row mins here
sum(apply(table(wisc.hclust.clusters, diagnosis), 1, min))

wisc.pr.hclust <- hclust(dist(wisc.pr$x[, 1:7]), method = "complete")

# Cut model into 4 clusters: wisc.pr.hclust.clusters
wisc.pr.hclust.clusters <- cutree(wisc.pr.hclust, k = 4)

wisc.km <- kmeans(scale(wisc.data), centers = 2, nstart = 20)

# Compare to actual diagnoses
t <- table(wisc.pr.hclust.clusters, diagnosis)
t
 
sum(apply(t, 1, min))
t <- table(wisc.km$cluster, diagnosis)
t

sum(apply(t, 1, min))
```



